-- vim.cmd("colorscheme catppuccin")

-- require("catppuccin").setup({
--     term_colors = false,
--     transparent_background = false,
--     styles = {
--         comments = {},
--         conditionals = {},
--         loops = {},
--         functions = {},
--         keywords = {},
--         strings = {},
--         variables = {},
--         numbers = {},
--         booleans = {},
--         properties = {},
--         types = {},
--     },
--     color_overrides = {
--         mocha = {
--             base = "#000000",
--             mantle = "#000000",
--             crust = "#000000",
--         },
--     }
-- })
